/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface MysteryGardenInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "calculateGrowth"
      | "getGrowth"
      | "getOwnerPlant"
      | "getOwnerPlantCount"
      | "getPlantInfo"
      | "getPlantParameters"
      | "markAsMature"
      | "ownerPlants"
      | "plant"
      | "plants"
      | "protocolId"
      | "totalPlants"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "PlantGrown" | "PlantMatured" | "PlantPlanted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "calculateGrowth",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getGrowth",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOwnerPlant",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOwnerPlantCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlantInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlantParameters",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "markAsMature",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerPlants",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "plant",
    values: [BytesLike, BytesLike, BytesLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "plants",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalPlants",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "calculateGrowth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getGrowth", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getOwnerPlant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOwnerPlantCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlantInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlantParameters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "markAsMature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownerPlants",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "plant", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "plants", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalPlants",
    data: BytesLike
  ): Result;
}

export namespace PlantGrownEvent {
  export type InputTuple = [plantId: BigNumberish, growthValue: BigNumberish];
  export type OutputTuple = [plantId: bigint, growthValue: bigint];
  export interface OutputObject {
    plantId: bigint;
    growthValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlantMaturedEvent {
  export type InputTuple = [plantId: BigNumberish, owner: AddressLike];
  export type OutputTuple = [plantId: bigint, owner: string];
  export interface OutputObject {
    plantId: bigint;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlantPlantedEvent {
  export type InputTuple = [plantId: BigNumberish, owner: AddressLike];
  export type OutputTuple = [plantId: bigint, owner: string];
  export interface OutputObject {
    plantId: bigint;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MysteryGarden extends BaseContract {
  connect(runner?: ContractRunner | null): MysteryGarden;
  waitForDeployment(): Promise<this>;

  interface: MysteryGardenInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  calculateGrowth: TypedContractMethod<
    [plantId: BigNumberish, timeEncrypted: BytesLike, timeProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getGrowth: TypedContractMethod<[plantId: BigNumberish], [string], "view">;

  getOwnerPlant: TypedContractMethod<
    [owner: AddressLike, index: BigNumberish],
    [bigint],
    "view"
  >;

  getOwnerPlantCount: TypedContractMethod<
    [owner: AddressLike],
    [bigint],
    "view"
  >;

  getPlantInfo: TypedContractMethod<
    [plantId: BigNumberish],
    [
      [string, bigint, boolean] & {
        owner: string;
        plantedAt: bigint;
        isMature: boolean;
      }
    ],
    "view"
  >;

  getPlantParameters: TypedContractMethod<
    [plantId: BigNumberish],
    [
      [string, string, string, string] & {
        weather: string;
        fertility: string;
        waterLevel: string;
        growth: string;
      }
    ],
    "view"
  >;

  markAsMature: TypedContractMethod<
    [plantId: BigNumberish],
    [void],
    "nonpayable"
  >;

  ownerPlants: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  plant: TypedContractMethod<
    [
      weatherEncrypted: BytesLike,
      fertilityEncrypted: BytesLike,
      waterLevelEncrypted: BytesLike,
      weatherProof: BytesLike,
      fertilityProof: BytesLike,
      waterLevelProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  plants: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, string, string, bigint, boolean] & {
        weather: string;
        fertility: string;
        waterLevel: string;
        growth: string;
        owner: string;
        plantedAt: bigint;
        isMature: boolean;
      }
    ],
    "view"
  >;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  totalPlants: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "calculateGrowth"
  ): TypedContractMethod<
    [plantId: BigNumberish, timeEncrypted: BytesLike, timeProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getGrowth"
  ): TypedContractMethod<[plantId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getOwnerPlant"
  ): TypedContractMethod<
    [owner: AddressLike, index: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOwnerPlantCount"
  ): TypedContractMethod<[owner: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPlantInfo"
  ): TypedContractMethod<
    [plantId: BigNumberish],
    [
      [string, bigint, boolean] & {
        owner: string;
        plantedAt: bigint;
        isMature: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPlantParameters"
  ): TypedContractMethod<
    [plantId: BigNumberish],
    [
      [string, string, string, string] & {
        weather: string;
        fertility: string;
        waterLevel: string;
        growth: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "markAsMature"
  ): TypedContractMethod<[plantId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "ownerPlants"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "plant"
  ): TypedContractMethod<
    [
      weatherEncrypted: BytesLike,
      fertilityEncrypted: BytesLike,
      waterLevelEncrypted: BytesLike,
      weatherProof: BytesLike,
      fertilityProof: BytesLike,
      waterLevelProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "plants"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, string, string, bigint, boolean] & {
        weather: string;
        fertility: string;
        waterLevel: string;
        growth: string;
        owner: string;
        plantedAt: bigint;
        isMature: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalPlants"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "PlantGrown"
  ): TypedContractEvent<
    PlantGrownEvent.InputTuple,
    PlantGrownEvent.OutputTuple,
    PlantGrownEvent.OutputObject
  >;
  getEvent(
    key: "PlantMatured"
  ): TypedContractEvent<
    PlantMaturedEvent.InputTuple,
    PlantMaturedEvent.OutputTuple,
    PlantMaturedEvent.OutputObject
  >;
  getEvent(
    key: "PlantPlanted"
  ): TypedContractEvent<
    PlantPlantedEvent.InputTuple,
    PlantPlantedEvent.OutputTuple,
    PlantPlantedEvent.OutputObject
  >;

  filters: {
    "PlantGrown(uint256,uint256)": TypedContractEvent<
      PlantGrownEvent.InputTuple,
      PlantGrownEvent.OutputTuple,
      PlantGrownEvent.OutputObject
    >;
    PlantGrown: TypedContractEvent<
      PlantGrownEvent.InputTuple,
      PlantGrownEvent.OutputTuple,
      PlantGrownEvent.OutputObject
    >;

    "PlantMatured(uint256,address)": TypedContractEvent<
      PlantMaturedEvent.InputTuple,
      PlantMaturedEvent.OutputTuple,
      PlantMaturedEvent.OutputObject
    >;
    PlantMatured: TypedContractEvent<
      PlantMaturedEvent.InputTuple,
      PlantMaturedEvent.OutputTuple,
      PlantMaturedEvent.OutputObject
    >;

    "PlantPlanted(uint256,address)": TypedContractEvent<
      PlantPlantedEvent.InputTuple,
      PlantPlantedEvent.OutputTuple,
      PlantPlantedEvent.OutputObject
    >;
    PlantPlanted: TypedContractEvent<
      PlantPlantedEvent.InputTuple,
      PlantPlantedEvent.OutputTuple,
      PlantPlantedEvent.OutputObject
    >;
  };
}
